/// Flutter icons Agri
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Agri
///      fonts:
///       - asset: fonts/Agri.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Agri {
  Agri._();

  static const _kFontFam = 'Agri';

  static const IconData mapsflags = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData shopping_cart = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData shopping_list = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe804, fontFamily: _kFontFam);
}
